### ISSUE TITLE
compilation error : solved

### ISSUE THREAD

**Issue by tissatussa** [Dannyj1/Zagreus#56]
i see you worked on the evaluation functions .. when i compile this newest version (it says v3.0!) i get a compile error in evaluate.cpp _no matching function for call to 'min'_ :

`uint8_t pawnShieldCount = std::min(popcnt(pawnShield), 3ULL);`

i solved it by :

`uint8_t pawnShieldCount = std::min<int>(popcnt(pawnShield), 3ULL);`

this solution i found at https://www.appsloveworld.com/cplus/100/155/no-matching-function-for-call-to-minuint8-t-int but i'm not into C(++) so this might be wrong .. probably the error is caused by the 2 parameters not having the same type.

[ i'm on Xubuntu 22.04 ]

**Comment by Dannyj1** [comment]
Thanks! I just ran into this as well trying to compile on Linux for the v3 version that I will be releasing soon, but hadn't been able to fix this yet. For some reason it doesn't happen on any if my Windows machines.

**Comment by tissatussa** [comment]
OK !
btw. this appears two times in evaluate.cpp but you'll have noticed that :-)

**Comment by tissatussa** [comment]
the new version 3.0 compiles OK on Linux.
i have a question / suggestion .. your README states we should set these variables before doing `cmake` commands :

```
export CC=/usr/bin/clang-15
export CXX=/usr/bin/clang++-15
```

can these lines be part of the make process ?
that would be logical and convenient.

**Comment by Dannyj1** [comment]
> the new version 3.0 compiles OK on Linux. i have a question / suggestion .. your README states we should set these variables before doing `cmake` commands :
> 
> ```
> export CC=/usr/bin/clang-15
> export CXX=/usr/bin/clang++-15
> ```
> 
> can these lines be part of the make process ? that would be logical and convenient.

I will see what I can do. I am not very familiar with cmake so I am not sure what is possible. It would indeed be nice to automate that, so thanks for the suggestion!
