### ISSUE TITLE
memory problem

### ISSUE THREAD

**Issue by tissatussa** [Dannyj1/Zagreus#57]
letting the newest v3.0 (after PR 54) play in CuteChess i see Zagreus is using too much memory : it increases after each move, upto several Gb (5.9) and i had to cancel the game to keep my PC running .. i set 128 Mb hash for all engines, most of them claim that amount of memory (a bit more) to run.

[ i'm on Xubuntu 22.04 ]

**Comment by Dannyj1** [comment]
Was already on it solved it in the most recent commit. (My whole PC locked up during testing at some point). This somehow slipped through during testing.

Thanks for reporting this! I am soon going to create a development branch to prevent problems like these getting into the master branch.
