### ISSUE TITLE
Zagreus 0.5 and 1.1.0 Hash

### ISSUE THREAD

**Issue by CPagador** [Dannyj1/Zagreus#75]
Zagreus 0.5 uses around 4GB of hash according to the task manager. Zagreus 1.1.0 uses 1GB. Atlhough WB GUI is set up for engines to use only 128 MB. I also tried Arena and CuteChess and the hash could not be set. Is there a way to configure it to use 128MB or less?

**Comment by Dannyj1** [comment]
I don't remember exactly, but I am pretty sure that some of the older versions (below 2.0 at the very least) didn't set the transposition table size properly or that they worked properly at all. I don't think there is a way to fix that unfortunately.

The older versions are fairly buggy in general. I solved many issues at some point by rewriting a big part of the code, including the transposition table.
